import type { MenuItem } from "./types";

export const CLOSE = 17;
export const ALLERGENS = ["Gluten", "Dairy", "Egg", "Fish", "Nuts", "Soya"];

export const SECTION_ORDER = [
  "Breakfast Butties",
  "All-Day Sandwiches",
  "Lunch Specials",
  "Juices & Drinks",
] as const;

export const SANDWICH_SECTIONS = new Set<string>([
  "Breakfast Butties",
  "All-Day Sandwiches",
  "Lunch Specials",
]);

export function isSandwichSection(section: string): boolean {
  return SANDWICH_SECTIONS.has(section);
}

export const SECTION_SHORT: Record<string, string> = {
  "Breakfast Butties": "Breakfast",
  "All-Day Sandwiches": "Sandwiches",
  "Lunch Specials": "Lunch",
  "Juices & Drinks": "Drinks",
};

export function sectionAnchor(name: string) {
  return `menu-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
}

export const SECTION_NOTES: Record<string, string> = {
  "Breakfast Butties": "Served 8am – 11am",
  "All-Day Sandwiches": "Served 8am – close",
  "Lunch Specials": "Hot, made fresh 11am – 2pm",
  "Juices & Drinks": "Pressed fresh, all day",
};

export const SEED: MenuItem[] = [
  {
    id: "b1",
    section: "Breakfast Butties",
    name: "The Full English Bap",
    desc: "Sausage, streaky bacon, fried egg, brown sauce, soft white bap",
    price: 5.9,
    from: 8,
    to: 11,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Egg"],
    remove: ["Sausage", "Bacon", "Egg", "Brown sauce"],
    extras: [
      { n: "Extra bacon", p: 1.2 },
      { n: "Hash brown", p: 1.0 },
      { n: "Cheese", p: 0.8 },
    ],
  },
  {
    id: "b2",
    section: "Breakfast Butties",
    name: "Bacon & Egg Muffin",
    desc: "Smoked back bacon, fried egg, English muffin",
    price: 4.5,
    from: 8,
    to: 11,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Egg"],
    remove: ["Bacon", "Egg"],
    extras: [
      { n: "Extra bacon", p: 1.2 },
      { n: "Cheese", p: 0.8 },
    ],
  },
  {
    id: "b3",
    section: "Breakfast Butties",
    name: "Veggie Breakfast",
    desc: "Hash brown, halloumi, grilled tomato, egg, ciabatta",
    price: 5.5,
    from: 8,
    to: 11,
    soldOut: false,
    veg: true,
    allergens: ["Gluten", "Dairy", "Egg"],
    remove: ["Halloumi", "Tomato", "Egg"],
    extras: [{ n: "Avocado", p: 1.5 }],
  },
  {
    id: "a1",
    section: "All-Day Sandwiches",
    name: "The Classic Cheese & Pickle",
    desc: "Mature cheddar, Branston, butter, thick white bloomer",
    price: 4.8,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: true,
    allergens: ["Gluten", "Dairy"],
    remove: ["Pickle", "Butter"],
    extras: [
      { n: "Extra cheese", p: 0.8 },
      { n: "Ham", p: 1.5 },
    ],
  },
  {
    id: "a2",
    section: "All-Day Sandwiches",
    name: "Coronation Chicken",
    desc: "Poached chicken, mild curried mayo, sultanas, little gem",
    price: 5.9,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Egg"],
    remove: ["Sultanas", "Little gem"],
    extras: [],
  },
  {
    id: "a3",
    section: "All-Day Sandwiches",
    name: "Tuna Melt Toastie",
    desc: "Tuna, red onion, melted cheddar, toasted sourdough",
    price: 5.6,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Dairy", "Fish"],
    remove: ["Red onion"],
    extras: [{ n: "Jalapeños", p: 0.5 }],
  },
  {
    id: "a4",
    section: "All-Day Sandwiches",
    name: "Hummus & Roast Veg",
    desc: "Roasted peppers, courgette, hummus, rocket, ciabatta",
    price: 5.2,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: true,
    allergens: ["Gluten"],
    remove: ["Rocket", "Courgette"],
    extras: [
      { n: "Halloumi", p: 1.5 },
      { n: "Avocado", p: 1.5 },
    ],
  },
  {
    id: "s1",
    section: "Lunch Specials",
    name: "Slow-Cooked Pulled Beef",
    desc: "12hr braised beef, horseradish crème, crispy onions, brioche roll",
    price: 7.9,
    from: 11,
    to: 14,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Dairy"],
    remove: ["Horseradish crème", "Crispy onions"],
    extras: [
      { n: "Extra beef", p: 2.0 },
      { n: "Cheese", p: 0.8 },
    ],
  },
  {
    id: "s2",
    section: "Lunch Specials",
    name: "Meatball Marinara Sub",
    desc: "Pork & beef meatballs, marinara, melted mozzarella, baguette",
    price: 7.5,
    from: 11,
    to: 14,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Dairy"],
    remove: ["Mozzarella"],
    extras: [{ n: "Extra meatballs", p: 2.0 }],
  },
  {
    id: "s3",
    section: "Lunch Specials",
    name: "Buttermilk Chicken",
    desc: "Fried chicken thigh, slaw, sriracha mayo, toasted bun",
    price: 7.2,
    from: 11,
    to: 14,
    soldOut: false,
    veg: false,
    allergens: ["Gluten", "Dairy", "Egg"],
    remove: ["Slaw", "Sriracha mayo"],
    extras: [{ n: "Extra chicken", p: 2.0 }],
  },
  {
    id: "j1",
    section: "Juices & Drinks",
    name: "Green Machine",
    desc: "Apple, cucumber, spinach, celery, lemon, ginger",
    price: 4.5,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: true,
    allergens: [],
    remove: ["Ginger"],
    extras: [],
  },
  {
    id: "j2",
    section: "Juices & Drinks",
    name: "Beetroot Booster",
    desc: "Beetroot, apple, carrot, orange",
    price: 4.5,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: true,
    allergens: [],
    remove: [],
    extras: [],
  },
  {
    id: "j3",
    section: "Juices & Drinks",
    name: "Flat White",
    desc: "House espresso blend",
    price: 3.0,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: true,
    allergens: ["Dairy"],
    remove: [],
    extras: [
      { n: "Extra shot", p: 0.5 },
      { n: "Oat milk", p: 0.4 },
    ],
  },
  {
    id: "j4",
    section: "Juices & Drinks",
    name: "Fresh Orange",
    desc: "Squeezed to order",
    price: 3.8,
    from: 8,
    to: CLOSE,
    soldOut: false,
    veg: true,
    allergens: [],
    remove: [],
    extras: [],
  },
];
